from pathlib import Path

DEFAULT_DATA_DIR = Path('./data')

DEFAULT_VOXCELEB_DATASET_DIR = DEFAULT_DATA_DIR / 'voxceleb'
DEFAULT_VOX1_AUDIO_DIR = DEFAULT_VOXCELEB_DATASET_DIR / 'vox1' / 'wav'
DEFAULT_VOX1TEST_AUDIO_DIR = DEFAULT_VOXCELEB_DATASET_DIR / 'vox1_test' / 'wav'
DEFAULT_VOX2_AUDIO_DIR = DEFAULT_VOXCELEB_DATASET_DIR / 'vox2' / 'wav'

DEFAULT_VOXCELEB_DATASET_OUTPUT_DIR = DEFAULT_DATA_DIR / 'voxceleb-mel'
DEFAULT_VOX1_OUTPUT_DIR = DEFAULT_VOXCELEB_DATASET_OUTPUT_DIR / 'vox1'
DEFAULT_VOX1TEST_OUTPUT_DIR = DEFAULT_VOXCELEB_DATASET_OUTPUT_DIR / 'vox1_test'
DEFAULT_VOX2_OUTPUT_DIR = DEFAULT_VOXCELEB_DATASET_OUTPUT_DIR / 'vox2'

DEFAULT_VOXCELEB_MISLABELED_JSON_DIR = DEFAULT_DATA_DIR / 'voxceleb-mislabeled-json'
