stage: test # [train, test, nld]
device: "cuda"
---
data:
    train_path: '/home/yrb/code/speechbrain/data/voxceleb/vox2/spmel_single'
    test_path: '/home/yrb/code/speechbrain/data/voxceleb/vox1_test/spmel_single'
    nld_path: '/home/yrb/code/speechbrain/data/voxceleb/vox2/spmel_single'
    vox1_path: '/home/yrb/code/speechbrain/data/voxceleb/vox1/spmel_single'
    esc50_path: ''
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding sizes
---
train:
    debug: !!bool "false" #without saving
    restore: !!bool "false" #Resume training from previous model path
    noise_type: Permute # [Permute, Open, Mix]
    noise_level: 75 # [0, 20, 50, 75]
    N : 256 #Number of speakers in batch
    M : 1 #Number of utterances per speaker
    num_workers: 6 #number of workers for dataloader
    lr: 0.0001 
    optimizer: Adam # "Adam"
    loss: AAMSC # [CE, GE2E, AAM, AAMSC]
    s: 15
    m: 0.1
    K: 3
    epochs: 3200 #Max training speaker epoch 
    log_interval: 20 #Epochs before printing progress
    checkpoint_interval: 40 #Save model after x speaker epochs
    checkpoint_dir: /home/yrb/code/speechbrain/data/models/
    model_path: 
---
test:
    N : 10 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 1 #number of workers for data laoder
    epochs: 300 #testing speaker epochs
    model_path: /home/yrb/code/speechbrain/data/models/Permute/
    # /home/yrb/code/speechbrain/data/models/Open/
---
nld: # noisy label detection
    noise_type: Permute # [Permute, Open, Mix]
    noise_level: 20 # [0, 20, 50, 75]
    model_path: /home/yrb/code/speechbrain/data/models/Permute/
    ######## GE2E ##############
    # /home/yrb/code/speechbrain/data/models/Permute/GE2E/0%/m4_bs128/ckpt_epoch_400.pth
    # /home/yrb/code/speechbrain/data/models/Permute/GE2E/20%/m8_bs128/ckpt_epoch_200.pth
    # /home/yrb/code/speechbrain/data/models/Permute/GE2E/50%/m8_bs128/ckpt_epoch_200.pth
    # /home/yrb/code/speechbrain/data/models/Permute/GE2E/75%/m16_bs128/ckpt_epoch_100.pth

    # /home/yrb/code/speechbrain/data/models/Open/GE2E/20%/m8_bs256/ckpt_epoch_400.pth
    ######## Softmax #############
    # /home/yrb/code/speechbrain/data/models/Permute/Softmax/0%/bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/Softmax/20%/bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/Softmax/50%/bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/Softmax/75%/bs128/ckpt_epoch_1600.pth
    ####### AAMSC ##################
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/20%/m0.1_s15_k10_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/50%/m0.1_s15_k10_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/50%/m0.1_s15_k20_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/75%/m0.1_s15_k10_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/75%/m0.1_s15_k10_bs128/ckpt_epoch_1600.pth
    
    ####### AAM ##################
    # /home/yrb/code/speechbrain/data/models/Permute/AAM/20%/m0.1_s15_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/20%/m0.1_s15_k3_bs128/ckpt_epoch_3200.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAM/50%/m0.1_s15_bs128/ckpt_epoch_1600.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAM/75%/m0.1_s15_bs256/ckpt_epoch_3200.pth

    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/0%/m0.1_s15_k3_bs256/ckpt_epoch_3200.pth
    # /home/yrb/code/speechbrain/data/models/Permute/AAMSC/20%/m0.1_s15_k3_bs128/ckpt_epoch_3200.pth
    
    N : 1 #Number of speakers in batch
    M : -1 #Number of utterances per speaker (-1 means all)
    num_workers: 1 #number of workers for dataloader