training: !!bool "false"
device: "cuda"
unprocessed_data: '/home/lizeqian/data4t/database_minh/*/*.wav'
---
data:
    train_path: '/media/mnpham/Hard Disk 2/train_tisv'
    train_path_unprocessed: '/media/mnpham/Lacie/self-supervision-train-clean-split-reversed/*'
    test_path: '/media/mnpham/Hard Disk 2/test_tisv'
    test_path_unprocessed: '/media/mnpham/Hard Disk 2/TIMIT/data/lisa/data/timit/raw/TIMIT/TRAIN_SORTED/*'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding sizes
    
    model_path: '/media/mnpham/Hard Disk 3/VoxCelebCorrupted/Experiment2/Debug/Duplicate=4&Chance=0.75/final_epoch_400_batch_id_1498.model'
    # model_path: "./speech_id_checkpoint/VoxCeleb2_2/final_epoch_400_batch_id_1498.model"
    #model_path: './speech_id_checkpoint/VoxCeleb2_BookTubeSpeech_ver1/ckpt_epoch_160_batch_id_3245.pth' #'speech_id_checkpoint/final_epoch_100_batch_id_1498.model' #Model path for testing, inference, or resuming training
---
train:
    N : 6 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 8 #number of workers for dataloader
    lr: 0.01 
    epochs: 100 #Max training speaker epoch 
    log_interval: 20 #Epochs before printing progress
    log_file: '/media/mnpham/Hard Disk 3/VoxCelebCorrupted/Experiment2/Debug/Duplicate=4&Chance=0.75/Stats'
    checkpoint_interval: 20 #Save model after x speaker epochs
    checkpoint_dir: '/media/mnpham/Hard Disk 3/VoxCelebCorrupted/Experiment2/Debug/Duplicate=4&Chance=0.75'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 10 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 300 #testing speaker epochs
