training: !!bool "true"
device: "cuda"
unprocessed_data: '/home/lizeqian/data4t/database_minh/*/*.wav'
---
data:
    train_path: '/home/yrb/code/speechbrain/data/voxceleb/vox2/spmel_single'  #'/media/mnpham/Hard Disk 3/WPI Research Data/ReversedPredictionData'
    train_path_unprocessed: '/home/yrb/code/speechbrain/data/voxceleb/vox2/aac'
    # test_path: '/home/yrb/code/speechbrain/data/test_tisv'
    # test_path_unprocessed: '/media/mnpham/Hard Disk 2/TIMIT/data/lisa/data/timit/raw/TIMIT/TRAIN_SORTED/*'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding sizes
    
    model_path: '/home/yrb/code/speechbrain/data/models/Permute/Softmax/SoftmaxExperiment7/final.model'
    # model_path: "./speech_id_checkpoint/VoxCeleb2_2/final_epoch_400_batch_id_1498.model"
    #model_path: './speech_id_checkpoint/VoxCeleb2_BookTubeSpeech_ver1/ckpt_epoch_160_batch_id_3245.pth' #'speech_id_checkpoint/final_epoch_100_batch_id_1498.model' #Model path for testing, inference, or resuming training
---
train:
    N : 64 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 12 #number of workers for dataloader
    lr: 0.0001 
    epochs: 400 #Max training speaker epoch 
    log_interval: 20 #Epochs before printing progress
    log_file: '/home/yrb/code/speechbrain/data/models/Permute/Softmax/SoftmaxExperiment7/Chance=0.1/Stats'
    checkpoint_interval: 20 #Save model after x speaker epochs
    checkpoint_dir: '/home/yrb/code/speechbrain/data/models/Permute/Softmax/SoftmaxExperiment7/Chance=0.1'
    restore: !!bool "false" #Resume training from previous model path
    test_loader_speed: !!bool "false"
---
test:
    N : 10 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 300 #testing speaker epochs
