training: !!bool "false"
device: "cuda"
---
data:
    train_path: '/media/mnpham/Hard Disk 2/train_tisv'
    test_path: '/media/mnpham/Hard Disk 2/test_tisv'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding sizes
    model_path: './model/final.model'
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 8 #number of workers for dataloader
    lr: 0.01 
    epochs: 400 #Max training speaker epoch 
    log_interval: 20 #Epochs before printing progress
    checkpoint_interval: 20 #Save model after x speaker epochs
    checkpoint_dir: './model/'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 10 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 300 #testing speaker epochs
